config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions"}

  root "static_pages#index"

  get 'careers', to: 'careers#index'
  get 'static_pages/portfolio'
  get 'team', to: 'static_pages#team'
  get 'products/outsourcing'
  get 'products/internal'
  get 'office/team', to: 'office/static_back_pages#team'
  get 'office/users/profile/:id', to: 'office/users#profile', as: 'office/user/profile'

  get 'office/years/:year_id/users/:id', to: 'office/users#salary', as: 'office/user/salary'

  get 'office/salaries/years/:id', to: 'office/salaries#year', as: 'office/salaries/year'
  get 'office/salaries/years/:year_id/months/:id', to: 'office/salaries#month', as: 'office/salaries/month'

  get 'office/invoices/years/:id', to: 'office/invoices#year', as: 'office/invoices/year'
  get 'office/invoices/years/:year_id/months/:id', to: 'office/invoices#month', as: 'office/invoices/month'
  get 'office/invoices/years/:year_id/months/:month_id/projects/:id', to: 'office/invoices#project', as: 'office/invoices/project'

  get 'office/docs', to: 'office/static_back_pages#docs'
  get 'office/dashboard', to: 'office/static_back_pages#index'

  resources :blogs do
    collection do
      post :index
      post :create_blog, to: "blogs#create", as: :create
    end
  end
  resources :forums do
    resources :comments
    collection do
      post :index
      post :create_forum, to: "forums#create", as: :create
    end
  end
  resources :flibraries
  resources :libraries do
    collection do
      post :index
      post :create_library, to: "libraries#create", as: :create
    end
  end
  resources :contacts
  resources :careers
  resources :rooms
  resources :products, except: :index
  resources :rooms do
    resources :messages
  end
  resources :salaries, only: [:create, :update, :destroy]
  resources :invoices, only: [:create, :update, :destroy]

  namespace :office do
    resources :users
    resources :teams
    resources :contacts
    resources :careers
    resources :rooms do
      resources :messages
    end
    resources :forums
    resources :products
    resources :salaries, only: [:new, :edit, :destroy]
    resources :invoices, only: [:new, :edit, :destroy]
    resources :libraries do
    collection do
      post :index
      post :create_library, to: "libraries#create", as: :create
     end
    end
    resources :blogs  do
      collection do
        post :index
        post :create_blog, to: "blog#create", as: :create
      end
    end
  end
end

app/models/invoice.rb
class Invoice < ApplicationRecord

  has_and_belongs_to_many :years
  has_and_belongs_to_many :months
  has_and_belongs_to_many :users
  has_and_belongs_to_many :products

  validates :time, presence: true, numericality: true, length: {maximum: 3}
  validates :rate, presence: true, numericality: true, length: {maximum: 3}

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  def create
    @invoice = Invoice.new(invoice_params)
    if @invoice.save
      redirect_to root_path, notice: "Invoice was successfully created."
    else
      render "office/invoices/new", status: :unprocessable_entity
    end
  end

  def update
    @invoice = Invoice.find(params[:id])
    if @invoice.update(invoice_params)
      redirect_to root_path, notice: "Invoice was successfully updated."
    else
      render "office/invoices/edit", status: :unprocessable_entity
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:time, :rate, month_ids:[], year_ids:[], user_ids:[], product_ids:[])
  end

end

app/controllers/office/blogs_controller.rb
class Office::BlogsController < OfficeController

  before_action :set_blog, only: %i[show edit destroy]

  def index
    @blogs = Blog.order(created_at: :desc)
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def show
  end

  def destroy
    @blog.destroy
    redirect_to office_blogs_path, status: :see_other, notice: "Blog was successfully destroyed."
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/controllers/office/careers_controller.rb
class Office::CareersController < OfficeController

  before_action :set_career, only: %i[show edit destroy]

  def index
    @careers = Career.order(created_at: :desc)
  end

  def show
  end

  def new
    @career = Career.new
  end

  def edit
  end

  def destroy
    @career.destroy
    redirect_to office_careers_path, status: :see_other, notice: "Career was successfully destroyed."
  end

  private

  def career_params
    params.require(:career).permit(:title, :requirement, :benefit, :salary, :work_load, :location, :status)
  end

  def set_career
    @career = Career.find(params[:id])
  end
end

app/controllers/office/contacts_controller.rb
class Office::ContactsController < OfficeController

  before_action :set_contact, only: %i[show edit destroy]

  def index
    @contacts = Contact.order(created_at: :desc)
  end

  def show
  end

  def edit
  end

  def destroy
    @contact.destroy
    redirect_to office_contacts_path, status: :see_other, notice: "Contact was successfully destroyed."
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :body, :email, :mobile, :status)
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end
end

app/controllers/office/flibraries_controller.rb
class Office::FlibrariesController < OfficeController
end

app/controllers/office/forums_controller.rb
class Office::ForumsController < OfficeController

  before_action :set_forum, only: %i[show edit update destroy]

  def index
    @forums = Forum.order(created_at: :desc)
  end

  def show
  end

  def new
    @forum = Forum.new
  end

  def create
    @forum = Forum.new(forum_params)
    if @forum.save
      redirect_to forums_path, notice: "Forum was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @forum.update(forum_params)
      redirect_to forum_path(@forum), notice: "Forum was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @forum.destroy
    redirect_to office_forums_path, status: :see_other, notice: "Forum was successfully destroyed."
  end

  private

  def set_forum
    @forum = Forum.find(params[:id])
  end

  def forum_params
    params.require(:forum).permit(:title, :body, :status, images:[])
  end

end

app/controllers/office/invoices_controller.rb
class Office::InvoicesController < OfficeController

  def year
    @years = Year.all
    @year = Year.find(params[:id])
    @months = Month.all
    @products = Product.all
    @invoices = Invoice.all
  end

  def month
    @month = Month.find(params[:id])
    @year = Year.find(params[:year_id])
    @products = Product.all
    @invoices = Invoice.all
  end

  def project
    @month = Month.find(params[:month_id])
    @year = Year.find(params[:year_id])
    @product = Product.find(params[:id])
    @users = User.all
    @invoices = Invoice.all
  end

  def new
    @invoice = Invoice.new
  end

  def edit
    @invoice = Invoice.find(params[:id])
  end

end

app/controllers/office/libraries_controller.rb
class Office::LibrariesController < OfficeController

  before_action :set_library, only: %i[show edit destroy]

  def index
    @libraries = Library.order(created_at: :desc)
  end

  def new
    @library = Library.new
  end

  def edit
  end

  def show
  end

  def destroy
    @library.destroy
    redirect_to office_libraries_path, status: :see_other, notice: "Library was successfully destroyed."
  end

  private

  def set_library
    @library = Library.find(params[:id])
  end
end

app/controllers/office/products_controller.rb
class Office::ProductsController < OfficeController

  before_action :set_product, only: %i[show edit update destroy]

  def index
    @internalps = Product.order(created_at: :desc)
  end

  def show
  end

  def new
    @internalp = Product.new
  end

  def edit
  end

  def destroy
   @internalp.destroy
   redirect_to office_products_path, status: :see_other, notice: "Product was successfully destroyed."
  end

  private

  def product_params
    params.require(:product).permit(:title, :content, :avatar, :status, :ptype, user_ids:[], images:[])
  end

  def set_product
    @internalp = Product.find(params[:id])
  end

end

app/controllers/office/rooms_controller.rb
class Office::RoomsController < OfficeController

  before_action :authenticate_user!

  def index
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)

    render "index"
  end

  def show
    @single_room = Room.find(params[:id])
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)
    @message = Message.new
    @messages = @single_room.messages.order(create_at: :asc)

    render "index"
  end

end

app/controllers/office/salaries_controller.rb
class Office::SalariesController < OfficeController

  def year
    @years = Year.all
    @year = Year.find(params[:id])
    @months = Month.all
    @users = User.where.not(work_group: "User")
    @salaries = Salary.all
  end

  def month
    @month = Month.find(params[:id])
    @year = Year.find(params[:year_id])
    @users = User.where.not(work_group: "User")
    @salaries = Salary.all
  end

  def project
    @user = User.find(params[:id])
    @months = Month.all
    @year = Year.find(params[:year_id])
  end

  def new
    @salary = Salary.new
  end

end

app/controllers/office/static_back_pages_controller.rb
class Office::StaticBackPagesController < OfficeController
  def index
  end

  def team
    @userspm = User.where(role: "Project Manager")
    @userswd = User.where(role: "Web Designer")
    @usersbd = User.where(role: "Back-end Developer")
    @usersfd = User.where(role: "Front-end Developer")
  end
end

app/controllers/office/users_controller.rb
class Office::UsersController < OfficeController

  def show
    @user = User.find(params[:id])
    @users = User.all_except(current_user)

    @room = Room.new
    @rooms = Room.public_rooms
    @room_name = get_name(@user, current_user)

    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)

    @message = Message.new
    @messages = @single_room.messages.order(create_at: :asc)

    render "office/rooms/index"
  end

  def profile
    @user = User.find(params[:id])
  end

  def salary
    @user = User.find(params[:id])
    @months = Month.all
    @year = Year.find(params[:year_id])
    @salaries = Salary.all
    @invoices = Invoice.all
  end

  private

  def get_name(user1, user2)
    user = [user1, user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end
end

app/controllers/office_controller.rb
class OfficeController < ApplicationController
  #before_action :authenticate_user!
end

app/views/office/invoices/edit.html.erb
<%= render "office/invoices/form" %>

app/views/office/invoices/month.html.erb
<div class="mt-20 flex items-center space-x-2 overflow-x-auto overflow-y-hidden justify-center flex-nowrap dark:text-gray-100">
  <div class="actions px-8 pt-4 mb-4"><%= link_to "Back", :back, class: "px-8 py-2 font-semibold border rounded border-white text-white cursor-pointer hover:border-blue-500 hover:text-blue-500" %></div>
</div>
<div class="flex justify-center mt-2 mx-auto my-20">
  <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
    <div class="min-w-full">
      <table class="w-full text-xs text-gray-500 dark:text-gray-400 text-center">
        <thead class="text-xs uppercase bg-gray-700 text-gray-400">
        <tr>
          <th colspan="8" class="py-3 px-2"><%= @year.name %> <%= @month.name %></th>
        </tr>
        <tr>
          <th scope="col" class="py-3 px-2">
            Projects
          </th>
          <th scope="col" class="py-3 px-6">
            Employees
          </th>
          <th scope="col" class="py-3 px-6">
            PM
          </th>
          <th scope="col" class="py-3 px-6">
            FD
          </th>
          <th scope="col" class="py-3 px-6">
            WD
          </th>
          <th scope="col" class="py-3 px-6">
            BD
          </th>
          <th scope="col" class="py-3 px-6">
            Total
          </th>
        </tr>
        </thead>
        <tbody>
        <% @products.each do |product| %>
        <% unless product.status == "passive" && product.invoices.empty? %>
          <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600 w-full text-sm text-gray-500">
            <div class=" border-gray-700 min-w-full" >
              <th scope="row" class="py-4 px-6 font-medium whitespace-nowrap text-white text-left">
                <%= link_to(office_invoices_project_path(@year, @month, product)) do %>
                  <%= product.title %>
                <% end %>
              </th>
              <td class="py-4 text-white">
                <% a = 0 %>
                <% product.invoices.each do |invoice| %>
                  <% if invoice.year_ids == [@year.id] && invoice.month_ids == [@month.id] %>
                    <% a += 1 %>
                  <% end %>
                <% end %>
                <%= a %>
              </td>
              <td class="py-4 text-white">
                <% a = 0 %>
                <% product.invoices.each do |invoice| %>
                  <% if invoice.year_ids == [@year.id] && invoice.month_ids == [@month.id] %>
                    <% invoice.users.each do |user| %>
                      <% if user.role == "Project Manager" %>
                        <% a += 1 %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
                <%= a %>
              </td>
              <td class="py-4 text-white">
                <% a = 0 %>
                <% product.invoices.each do |invoice| %>
                  <% if invoice.year_ids == [@year.id] && invoice.month_ids == [@month.id] %>
                    <% invoice.users.each do |user| %>
                      <% if user.role == "Front-end Developer" %>
                        <% a += 1 %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
                <%= a %>
              </td>
              <td class="py-4 text-white">
                <% a = 0 %>
                <% product.invoices.each do |invoice| %>
                  <% if invoice.year_ids == [@year.id] && invoice.month_ids == [@month.id] %>
                    <% invoice.users.each do |user| %>
                      <% if user.role == "Web Designer" %>
                        <% a += 1 %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
                <%= a %>
              </td>
              <td class="py-4 text-white">
                <% a = 0 %>
                <% product.invoices.each do |invoice| %>
                  <% if invoice.year_ids == [@year.id] && invoice.month_ids == [@month.id] %>
                    <% invoice.users.each do |user| %>
                      <% if user.role == "Back-end Developer" %>
                        <% a += 1 %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
                <%= a %>
              </td>
              <td class="py-4 text-white">
                <% a = 0 %>
                <% product.invoices.each do |invoice| %>
                  <% if invoice.year_ids == [@year.id] && invoice.month_ids == [@month.id] %>
                    <% a += invoice.rate * invoice.time %>
                  <% end %>
                <% end %>
                <%= a %>
              </td>
            </div>
          </tr>
        <% end %>
        <% end %>
        <tr>
          <th colspan="6" class="text-sm py-4 px-6 font-bold whitespace-nowrap text-white text-left">
            Total
          </th>
          <td class="py-4 text-white font-bold text-sm">
            <% a = 0 %>
            <% @invoices.each do |invoice| %>
              <% if invoice.year_ids == [@year.id] && invoice.month_ids == [@month.id] %>
                <% a += invoice.rate * invoice.time %>
              <% end %>
            <% end %>
            <%= a %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/office/invoices/new.html.erb
<%= render "office/invoices/form" %>

app/views/office/invoices/project.html.erb
<div class="mt-20 flex items-center space-x-2 overflow-x-auto overflow-y-hidden justify-center flex-nowrap dark:text-gray-100">
  <div class="actions px-8 pt-4 mb-4"><%= link_to "Back", :back, class: "px-8 py-2 font-semibold border rounded border-white text-white cursor-pointer hover:border-blue-500 hover:text-blue-500" %></div>
</div>
<div class="mt-20 flex items-center space-x-2 overflow-x-auto overflow-y-hidden justify-center flex-nowrap dark:text-gray-100">
  <div class="actions px-8 pt-4 mb-4"><%= link_to "Invoice", new_office_invoice_path, class: "px-8 py-2 font-semibold border rounded border-white text-white cursor-pointer hover:border-blue-500 hover:text-blue-500" %></div>
</div>
<div class="flex justify-center mt-2 mx-auto my-20">
  <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
    <div class="min-w-full">
      <table class="w-full text-xs text-gray-500 dark:text-gray-400 text-center">
        <thead class="text-xs uppercase bg-gray-700 text-gray-400">
        <tr>
          <th colspan="6" class="py-3 px-2"><%= @product.title %></th>
        </tr>
        <tr>
          <th scope="col" class="py-3 px-2">
            Employees
          </th>
          <th scope="col" class="py-3 px-6">
            Role
          </th>
          <th scope="col" class="py-3 px-6">
            Level
          </th>
          <th scope="col" class="py-3 px-6">
            Time
          </th>
          <th scope="col" class="py-3 px-6">
            Rate
          </th>
          <th scope="col" class="py-3 px-6">
            Total
          </th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <% unless user.invoices.empty? %>
            <% user.invoices.each do |invoice| %>
              <% if invoice.year_ids == [@year.id] && invoice.month_ids == [@month.id] && invoice.product_ids == [@product.id] %>
                <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600 w-full text-sm text-gray-500">
                  <div class=" border-gray-700 min-w-full" >
                    <th scope="row" class="py-4 px-6 font-medium whitespace-nowrap text-white text-left">
                      <%= link_to(office_user_salary_path(@year, user)) do %>
                        <%= user.name %> <%= user.last_name %>
                      <% end %>
                    </th>
                    <td class="py-4 text-white">
                      <%= user.role %>
                    </td>
                    <td class="py-4 text-white">
                      <%= user.level %>
                    </td>
                        <td class="py-4 text-white">
                          <%= invoice.time %>
                        </td>
                        <td class="py-4 text-white">
                          <%= invoice.rate %>
                        </td>
                        <td class="py-4 text-white">
                          <%= invoice.rate * invoice.time %>
                        </td>
                  </div>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
        <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600 w-full text-sm text-gray-500">
          <th colspan="5" class="text-sm py-4 px-6 font-bold whitespace-nowrap text-white text-left">
            Employees
          </th>
          <td class="py-4 text-white font-bold text-sm">
            <% a = 0 %>
            <% @product.invoices.each do |invoice| %>
              <% if invoice.year_ids == [@year.id] && invoice.month_ids == [@month.id] %>
                <% a += 1 %>
              <% end %>
            <% end %>
            <%= a %>
          </td>
        </tr>
        <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600 w-full text-sm text-gray-500">
          <th colspan="5" class="text-sm py-4 px-6 font-bold whitespace-nowrap text-white text-left">
            Total
          </th>
          <td class="py-4 text-white font-bold text-sm">
            <% a = 0 %>
            <% @invoices.each do |invoice| %>
              <% if invoice.year_ids == [@year.id] && invoice.month_ids == [@month.id] && invoice.product_ids == [@product.id] %>
                <% a += invoice.rate * invoice.time %>
              <% end %>
            <% end %>
            <%= a %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/office/invoices/year.html.erb
<div class="mt-20 flex items-center space-x-2 overflow-x-auto overflow-y-hidden justify-center flex-nowrap dark:text-gray-100">
  <div class="actions px-8 pt-4 mb-4"><%= link_to "Invoice", new_office_invoice_path, class: "px-8 py-2 font-semibold border rounded border-white text-white cursor-pointer hover:border-blue-500 hover:text-blue-500" %></div>
</div>
<div class="mt-4 flex items-center space-x-2 overflow-x-auto overflow-y-hidden justify-center flex-nowrap dark:text-gray-100">
  <% @years.each do |year| %>
    <div class="actions px-8 pt-4 mb-4">
      <%= link_to(office_invoices_year_path(year), class: "px-8 py-2 font-semibold border rounded border-white text-white cursor-pointer hover:border-blue-500 hover:text-blue-500") do %>
        <%= year.name %>
      <% end %>
    </div>
  <% end %>
</div>
<div class="flex justify-center mt-2 mx-auto my-20">
  <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
    <div class="min-w-full">
      <table class="w-full text-xs text-gray-500 dark:text-gray-400 text-center">
        <thead class="text-xs uppercase bg-gray-700 text-gray-400">
        <tr>
          <th></th>
          <th></th>
          <th colspan="12" class="py-3 px-2">Month</th>
          <th></th>
        </tr>
        <tr>
          <th scope="col" class="py-3 px-2">
            Projects
          </th>
          <th scope="col" class="py-3 px-2">
            Employees
          </th>
          <% @months.each do |month| %>
            <th scope="col" class="py-3 px-6">
              <%= link_to(office_invoices_month_path(@year, month)) do %>
                <%= month.id %>
              <% end %>
            </th>
          <% end %>
          <th scope="col" class="py-3 px-6">
            Total
          </th>
        </tr>
        </thead>
        <tbody>
        <% @products.each do |product| %>
          <% unless product.status == "passive" && product.invoices.empty? %>
            <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600 w-full text-sm text-gray-500">
              <div class=" border-gray-700 min-w-full" >
                <th scope="row" class="py-4 px-6 font-medium whitespace-nowrap text-white text-left">
                  <%= product.title %>
                </th>
                <td class="py-4 text-white">
                  <%= product.user_ids.size %>
                </td>
                <td class="py-4 text-white">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] && invoice.month_ids == [1] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
                <td class="py-4 text-white">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] && invoice.month_ids == [2] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
                <td class="py-4 text-white">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] && invoice.month_ids == [3] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
                <td class="py-4 text-white">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] && invoice.month_ids == [4] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
                <td class="py-4 text-white">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] && invoice.month_ids == [5] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
                <td class="py-4 text-white">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] && invoice.month_ids == [6] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
                <td class="py-4 text-white">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] && invoice.month_ids == [7] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
                <td class="py-4 text-white">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] && invoice.month_ids == [8] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
                <td class="py-4 text-white">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] && invoice.month_ids == [9] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
                <td class="py-4 text-white">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] && invoice.month_ids == [10] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
                <td class="py-4 text-white">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] && invoice.month_ids == [11] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
                <td class="py-4 text-white">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] && invoice.month_ids == [12] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
                <td class="py-4 text-white font-medium whitespace-nowrap">
                  <% a = 0 %>
                  <% product.invoices.each do |invoice| %>
                    <% if invoice.year_ids == [@year.id] %>
                      <% a += invoice.rate * invoice.time %>
                    <% end %>
                  <% end %>
                  <%= a %>
                </td>
              </div>
            </tr>
          <% end %>
        <% end %>
        <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600 w-full text-sm text-gray-500">
          <th colspan="14" class="py-4 px-6 font-medium whitespace-nowrap text-white text-left">
            Total
          </th>
          <td class="py-4 text-white font-medium">
            <% a = 0 %>
            <% @invoices.each do |invoice| %>
              <% if invoice.year_ids == [@year.id] %>
                <% a += invoice.rate * invoice.time %>
              <% end %>
            <% end %>
            <%= a %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>