config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions"}

  root "static_pages#index"

  get 'careers', to: 'careers#index'
  get 'static_pages/portfolio'
  get 'team', to: 'static_pages#team'
  get 'products/outsourcing'
  get 'products/internal'
  get 'office/team', to: 'office/static_back_pages#team'
  get 'office/users/profile/:id', to: 'office/users#profile', as: 'office/user/profile'

  get 'office/years/:year_id/users/:id', to: 'office/users#salary', as: 'office/user/salary'

  get 'office/salaries/years/:id', to: 'office/salaries#year', as: 'office/salaries/year'
  get 'office/salaries/years/:year_id/months/:id', to: 'office/salaries#month', as: 'office/salaries/month'

  get 'office/invoices/years/:id', to: 'office/invoices#year', as: 'office/invoices/year'
  get 'office/invoices/years/:year_id/months/:id', to: 'office/invoices#month', as: 'office/invoices/month'
  get 'office/invoices/years/:year_id/months/:month_id/projects/:id', to: 'office/invoices#project', as: 'office/invoices/project'

  get 'office/docs', to: 'office/static_back_pages#docs'
  get 'office/dashboard', to: 'office/static_back_pages#index'

  resources :blogs do
    collection do
      post :index
      post :create_blog, to: "blogs#create", as: :create
    end
  end
  resources :forums do
    resources :comments
    collection do
      post :index
      post :create_forum, to: "forums#create", as: :create
    end
  end
  resources :flibraries
  resources :libraries do
    collection do
      post :index
      post :create_library, to: "libraries#create", as: :create
    end
  end
  resources :contacts
  resources :careers
  resources :rooms
  resources :products, except: :index
  resources :rooms do
    resources :messages
  end
  resources :salaries, only: [:create, :update, :destroy]
  resources :invoices, only: [:create, :update, :destroy]

  namespace :office do
    resources :users
    resources :teams
    resources :contacts
    resources :careers
    resources :rooms do
      resources :messages
    end
    resources :forums
    resources :products
    resources :salaries, only: [:new, :edit, :destroy]
    resources :invoices, only: [:new, :edit, :destroy]
    resources :libraries do
    collection do
      post :index
      post :create_library, to: "libraries#create", as: :create
     end
    end
    resources :blogs  do
      collection do
        post :index
        post :create_blog, to: "blog#create", as: :create
      end
    end
  end
end

app/models/blog.rb
class Blog < ApplicationRecord

  has_many_attached :images
  has_one_attached :avatar

  validates :title, :body, presence: true
  validates :title, uniqueness: true, length: {maximum: 100}
  validates :body, length: {in: 100..3000}

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_blog, only: %i[show update]

  def index
    @blogs = Blog.all
    @pagy, @blogs = pagy_countless(Blog.order(created_at: :desc), items: 6)

    respond_to do |format|
      format.html # GET
      format.turbo_stream # POST
    end
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blog_path(@blog), notice: "Blog was successfully created."
    else
      render "office/blogs/new", status: :unprocessable_entity
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blog_path(@blog), notice: "Blog was successfully updated."
    else
      render "office/blogs/edit", status: :unprocessable_entity
    end
  end

  def show
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :body, :avatar, images:[])
  end
end

app/controllers/office/blogs_controller.rb
class Office::BlogsController < OfficeController

  before_action :set_blog, only: %i[show edit destroy]

  def index
    @blogs = Blog.order(created_at: :desc)
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def show
  end

  def destroy
    @blog.destroy
    redirect_to office_blogs_path, status: :see_other, notice: "Blog was successfully destroyed."
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/controllers/office/careers_controller.rb
class Office::CareersController < OfficeController

  before_action :set_career, only: %i[show edit destroy]

  def index
    @careers = Career.order(created_at: :desc)
  end

  def show
  end

  def new
    @career = Career.new
  end

  def edit
  end

  def destroy
    @career.destroy
    redirect_to office_careers_path, status: :see_other, notice: "Career was successfully destroyed."
  end

  private

  def career_params
    params.require(:career).permit(:title, :requirement, :benefit, :salary, :work_load, :location, :status)
  end

  def set_career
    @career = Career.find(params[:id])
  end
end

app/controllers/office/contacts_controller.rb
class Office::ContactsController < OfficeController

  before_action :set_contact, only: %i[show edit destroy]

  def index
    @contacts = Contact.order(created_at: :desc)
  end

  def show
  end

  def edit
  end

  def destroy
    @contact.destroy
    redirect_to office_contacts_path, status: :see_other, notice: "Contact was successfully destroyed."
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :body, :email, :mobile, :status)
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end
end

app/controllers/office/flibraries_controller.rb
class Office::FlibrariesController < OfficeController
end

app/controllers/office/forums_controller.rb
class Office::ForumsController < OfficeController

  before_action :set_forum, only: %i[show edit update destroy]

  def index
    @forums = Forum.order(created_at: :desc)
  end

  def show
  end

  def new
    @forum = Forum.new
  end

  def create
    @forum = Forum.new(forum_params)
    if @forum.save
      redirect_to forums_path, notice: "Forum was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @forum.update(forum_params)
      redirect_to forum_path(@forum), notice: "Forum was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @forum.destroy
    redirect_to office_forums_path, status: :see_other, notice: "Forum was successfully destroyed."
  end

  private

  def set_forum
    @forum = Forum.find(params[:id])
  end

  def forum_params
    params.require(:forum).permit(:title, :body, :status, images:[])
  end

end

app/controllers/office/invoices_controller.rb
class Office::InvoicesController < OfficeController

  def year
    @years = Year.all
    @year = Year.find(params[:id])
    @months = Month.all
    @products = Product.all
    @invoices = Invoice.all
  end

  def month
    @month = Month.find(params[:id])
    @year = Year.find(params[:year_id])
    @products = Product.all
    @invoices = Invoice.all
  end

  def project
    @month = Month.find(params[:month_id])
    @year = Year.find(params[:year_id])
    @product = Product.find(params[:id])
    @users = User.all
    @invoices = Invoice.all
  end

  def new
    @invoice = Invoice.new
  end

  def edit
    @invoice = Invoice.find(params[:id])
  end

end

app/controllers/office/libraries_controller.rb
class Office::LibrariesController < OfficeController

  before_action :set_library, only: %i[show edit destroy]

  def index
    @libraries = Library.order(created_at: :desc)
  end

  def new
    @library = Library.new
  end

  def edit
  end

  def show
  end

  def destroy
    @library.destroy
    redirect_to office_libraries_path, status: :see_other, notice: "Library was successfully destroyed."
  end

  private

  def set_library
    @library = Library.find(params[:id])
  end
end

app/controllers/office/products_controller.rb
class Office::ProductsController < OfficeController

  before_action :set_product, only: %i[show edit update destroy]

  def index
    @internalps = Product.order(created_at: :desc)
  end

  def show
  end

  def new
    @internalp = Product.new
  end

  def edit
  end

  def destroy
   @internalp.destroy
   redirect_to office_products_path, status: :see_other, notice: "Product was successfully destroyed."
  end

  private

  def product_params
    params.require(:product).permit(:title, :content, :avatar, :status, :ptype, user_ids:[], images:[])
  end

  def set_product
    @internalp = Product.find(params[:id])
  end

end

app/controllers/office/rooms_controller.rb
class Office::RoomsController < OfficeController

  before_action :authenticate_user!

  def index
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)

    render "index"
  end

  def show
    @single_room = Room.find(params[:id])
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)
    @message = Message.new
    @messages = @single_room.messages.order(create_at: :asc)

    render "index"
  end

end

app/controllers/office/salaries_controller.rb
class Office::SalariesController < OfficeController

  def year
    @years = Year.all
    @year = Year.find(params[:id])
    @months = Month.all
    @users = User.where.not(work_group: "User")
    @salaries = Salary.all
  end

  def month
    @month = Month.find(params[:id])
    @year = Year.find(params[:year_id])
    @users = User.where.not(work_group: "User")
    @salaries = Salary.all
  end

  def project
    @user = User.find(params[:id])
    @months = Month.all
    @year = Year.find(params[:year_id])
  end

  def new
    @salary = Salary.new
  end

end

app/controllers/office/static_back_pages_controller.rb
class Office::StaticBackPagesController < OfficeController
  def index
  end

  def team
    @userspm = User.where(role: "Project Manager")
    @userswd = User.where(role: "Web Designer")
    @usersbd = User.where(role: "Back-end Developer")
    @usersfd = User.where(role: "Front-end Developer")
  end
end

app/controllers/office/users_controller.rb
class Office::UsersController < OfficeController

  def show
    @user = User.find(params[:id])
    @users = User.all_except(current_user)

    @room = Room.new
    @rooms = Room.public_rooms
    @room_name = get_name(@user, current_user)

    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)

    @message = Message.new
    @messages = @single_room.messages.order(create_at: :asc)

    render "office/rooms/index"
  end

  def profile
    @user = User.find(params[:id])
  end

  def salary
    @user = User.find(params[:id])
    @months = Month.all
    @year = Year.find(params[:year_id])
    @salaries = Salary.all
    @invoices = Invoice.all
  end

  private

  def get_name(user1, user2)
    user = [user1, user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end
end

app/controllers/office_controller.rb
class OfficeController < ApplicationController
  #before_action :authenticate_user!
end

app/views/office/blogs/_form.html.erb
<% if action_name == "new" %>

  <div class="w-full max-w-lg mx-auto mt-12">

    <%= render 'office/static_back_pages/errors', object: @blog %>

    <%= form_with(url: create_blogs_path, model: @blog) do |form| %>

      <div class="mb-6">
        <%= form.label :title, class: "block mb-2 text-sm font-medium text-gray-300" %>
        <%= form.text_field :title, required: true, class: "shadow-sm border text-sm rounded-md block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500 shadow-sm-light form-control", placeholder: "Title" %>
      </div>

      <div class="mb-6">
        <%= form.label :content, class: "block mb-2 text-sm font-medium text-gray-300" %>
        <%= form.text_area :body, required: true, class: "form-control shadow-sm border text-sm rounded-md block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500 shadow-sm-light", placeholder: "Content" %>
      </div>

      <div class="mb-6">
        <%= form.label :avatar, class: "block mb-2 text-sm font-medium text-gray-300" %>
        <%= form.file_field :avatar, class: "text-gray-300 text-sm"%>
      </div>

      <div class="mb-6">
        <%= form.label :images, class: "block mb-2 text-sm font-medium text-gray-300" %>
        <%= form.file_field :images, multiple: true, class: "text-gray-300 text-sm" %>
      </div>

      <%= form.submit "Submit", class: "px-8 py-2 font-semibold border rounded border-white text-white cursor-pointer hover:border-blue-500 hover:text-blue-500" %>

    <% end %>

  </div>

<% else %>

  <div class="w-full max-w-lg mx-auto mt-12">

    <%= render 'office/static_back_pages/errors', object: @blog %>

    <%= form_with model: @blog do |form| %>

      <div class="mb-6">
        <%= form.label :title, class: "block mb-2 text-sm font-medium text-gray-300" %>
        <%= form.text_field :title, required: true, class: "form-control shadow-sm border text-sm rounded-md block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500 shadow-sm-light", placeholder: "Title" %>
      </div>

      <div class="mb-6">
        <%= form.label :content, class: "block mb-2 text-sm font-medium text-gray-300" %>
        <%= form.text_area :body, required: true, class: "shadow-sm border text-sm rounded-md block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500 shadow-sm-light form-control", placeholder: "Content" %>
      </div>

      <div class="mb-6">
        <%= form.label :avatar, class: "block mb-2 text-sm font-medium text-gray-300" %>
        <%= form.file_field :avatar, class: "text-gray-300 text-sm"%>
      </div>

      <div class="mb-6">
        <%= form.label :images, class: "block mb-2 text-sm font-medium text-gray-300" %>
        <%= form.file_field :images, multiple: true, class: "text-gray-300 text-sm" %>
      </div>

      <%= form.submit "Submit", class: "px-8 py-2 font-semibold border rounded border-white text-white cursor-pointer hover:border-blue-500 hover:text-blue-500" %>

    <% end %>

  </div>

<% end %>

app/views/office/blogs/edit.html.erb
<%= render "form" %>

app/views/office/blogs/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">

<div class="mt-20 flex items-center space-x-2 overflow-x-auto overflow-y-hidden justify-center flex-nowrap dark:text-gray-100">
  <div class="actions px-8 pt-4 mb-4"><%= link_to "New", new_office_blog_path, class: "px-8 py-2 font-semibold border rounded border-white text-white cursor-pointer hover:border-blue-500 hover:text-blue-500" %></div>
</div>

<div class="flex justify-center mt-2 mx-auto">
  <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
    <div class="min-w-full">
      <table class="w-full text-sm text-gray-500 dark:text-gray-400 text-center">
        <thead class="text-xs uppercase bg-gray-700 text-gray-400">
        <tr>
          <th scope="col" class="py-3 px-6">
            Title
          </th>
          <th scope="col" class="py-3 px-6">
            Date
          </th>
          <th scope="col" class="py-3 px-6">
            Images
          </th>
          <th scope="col" class="py-3 px-6">
            Action
          </th>
        </tr>
        </thead>
        <tbody>
        <% @blogs.each do |blog| %>
          <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600 w-full text-sm text-center text-gray-500">
            <div class=" border-gray-700 min-w-full" >
              <th scope="row" class="py-4 px-6 font-medium whitespace-nowrap text-white">
                <%= blog.title %>
              </th>
              <td class="py-4 px-6">
                <%= blog.created_at.strftime("%d.%m.%Y") %>
              </td>
              <td class="py-4 px-6">
                <% if blog.images.attached? %>
                  <div class="flex flex-row-reverse justify-around -space-x-3 space-x-reverse">
                    <div class="flex flex-row-reverse justify-end -space-x-3 space-x-reverse">
                      <% blog.images.each do |image| %>
                        <div class="relative flex h-8 w-8 shrink-0 select-none items-center justify-center rounded-full bg-gray-100 text-sm font-bold uppercase text-gray-800 ring ring-yellow-500">
                          <%= image_tag image, class:"h-full w-full rounded-full object-cover object-center" %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </td>
              <td class="py-4 px-6">
                <%= link_to(blog_path(blog), class: "text-gray-400 hover:text-yellow-500 mr-2") do %>
                  <i class="material-icons-outlined text-base">visibility</i>
                <% end %>
                <%= link_to(edit_office_blog_path(blog), class: "text-gray-400 hover:text-yellow-500 mr-2") do %>
                  <i class="material-icons-outlined text-base">edit</i>
                <% end %>
                <%= link_to(office_blog_path(blog), data: { "turbo-method": :delete,
                                                            turbo_confirm: "You sure?" }, class: "text-gray-400 hover:text-yellow-500 mr-2") do %>
                  <i class="material-icons-round text-base">delete_outline</i>
                <% end %>
              </td>
            </div>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>









app/views/office/blogs/new.html.erb
<%= render "office/blogs/form" %>