config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions"}

  root "static_pages#index"

  get 'careers', to: 'careers#index'
  get 'static_pages/portfolio'
  get 'team', to: 'static_pages#team'
  get 'products/outsourcing'
  get 'products/internal'
  get 'office/team', to: 'office/static_back_pages#team'
  get 'office/users/profile/:id', to: 'office/users#profile', as: 'office/user/profile'

  get 'office/years/:year_id/users/:id', to: 'office/users#salary', as: 'office/user/salary'

  get 'office/salaries/years/:id', to: 'office/salaries#year', as: 'office/salaries/year'
  get 'office/salaries/years/:year_id/months/:id', to: 'office/salaries#month', as: 'office/salaries/month'

  get 'office/invoices/years/:id', to: 'office/invoices#year', as: 'office/invoices/year'
  get 'office/invoices/years/:year_id/months/:id', to: 'office/invoices#month', as: 'office/invoices/month'
  get 'office/invoices/years/:year_id/months/:month_id/projects/:id', to: 'office/invoices#project', as: 'office/invoices/project'

  get 'office/docs', to: 'office/static_back_pages#docs'
  get 'office/dashboard', to: 'office/static_back_pages#index'

  resources :blogs do
    collection do
      post :index
      post :create_blog, to: "blogs#create", as: :create
    end
  end
  resources :forums do
    resources :comments
    collection do
      post :index
      post :create_forum, to: "forums#create", as: :create
    end
  end
  resources :flibraries
  resources :libraries do
    collection do
      post :index
      post :create_library, to: "libraries#create", as: :create
    end
  end
  resources :contacts
  resources :careers
  resources :rooms
  resources :products, except: :index
  resources :rooms do
    resources :messages
  end
  resources :salaries, only: [:create, :update, :destroy]
  resources :invoices, only: [:create, :update, :destroy]

  namespace :office do
    resources :users
    resources :teams
    resources :contacts
    resources :careers
    resources :rooms do
      resources :messages
    end
    resources :forums
    resources :products
    resources :salaries, only: [:new, :edit, :destroy]
    resources :invoices, only: [:new, :edit, :destroy]
    resources :libraries do
    collection do
      post :index
      post :create_library, to: "libraries#create", as: :create
     end
    end
    resources :blogs  do
      collection do
        post :index
        post :create_blog, to: "blog#create", as: :create
      end
    end
  end
end

app/controllers/office/blogs_controller.rb
class Office::BlogsController < OfficeController

  before_action :set_blog, only: %i[show edit destroy]

  def index
    @blogs = Blog.order(created_at: :desc)
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def show
  end

  def destroy
    @blog.destroy
    redirect_to office_blogs_path, status: :see_other, notice: "Blog was successfully destroyed."
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/controllers/office/careers_controller.rb
class Office::CareersController < OfficeController

  before_action :set_career, only: %i[show edit destroy]

  def index
    @careers = Career.order(created_at: :desc)
  end

  def show
  end

  def new
    @career = Career.new
  end

  def edit
  end

  def destroy
    @career.destroy
    redirect_to office_careers_path, status: :see_other, notice: "Career was successfully destroyed."
  end

  private

  def career_params
    params.require(:career).permit(:title, :requirement, :benefit, :salary, :work_load, :location, :status)
  end

  def set_career
    @career = Career.find(params[:id])
  end
end

app/controllers/office/contacts_controller.rb
class Office::ContactsController < OfficeController

  before_action :set_contact, only: %i[show edit destroy]

  def index
    @contacts = Contact.order(created_at: :desc)
  end

  def show
  end

  def edit
  end

  def destroy
    @contact.destroy
    redirect_to office_contacts_path, status: :see_other, notice: "Contact was successfully destroyed."
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :body, :email, :mobile, :status)
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end
end

app/controllers/office/flibraries_controller.rb
class Office::FlibrariesController < OfficeController
end

app/controllers/office/forums_controller.rb
class Office::ForumsController < OfficeController

  before_action :set_forum, only: %i[show edit update destroy]

  def index
    @forums = Forum.order(created_at: :desc)
  end

  def show
  end

  def new
    @forum = Forum.new
  end

  def create
    @forum = Forum.new(forum_params)
    if @forum.save
      redirect_to forums_path, notice: "Forum was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @forum.update(forum_params)
      redirect_to forum_path(@forum), notice: "Forum was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @forum.destroy
    redirect_to office_forums_path, status: :see_other, notice: "Forum was successfully destroyed."
  end

  private

  def set_forum
    @forum = Forum.find(params[:id])
  end

  def forum_params
    params.require(:forum).permit(:title, :body, :status, images:[])
  end

end

app/controllers/office/invoices_controller.rb
class Office::InvoicesController < OfficeController

  def year
    @years = Year.all
    @year = Year.find(params[:id])
    @months = Month.all
    @products = Product.all
    @invoices = Invoice.all
  end

  def month
    @month = Month.find(params[:id])
    @year = Year.find(params[:year_id])
    @products = Product.all
    @invoices = Invoice.all
  end

  def project
    @month = Month.find(params[:month_id])
    @year = Year.find(params[:year_id])
    @product = Product.find(params[:id])
    @users = User.all
    @invoices = Invoice.all
  end

  def new
    @invoice = Invoice.new
  end

  def edit
    @invoice = Invoice.find(params[:id])
  end

end

app/controllers/office/libraries_controller.rb
class Office::LibrariesController < OfficeController

  before_action :set_library, only: %i[show edit destroy]

  def index
    @libraries = Library.order(created_at: :desc)
  end

  def new
    @library = Library.new
  end

  def edit
  end

  def show
  end

  def destroy
    @library.destroy
    redirect_to office_libraries_path, status: :see_other, notice: "Library was successfully destroyed."
  end

  private

  def set_library
    @library = Library.find(params[:id])
  end
end

app/controllers/office/products_controller.rb
class Office::ProductsController < OfficeController

  before_action :set_product, only: %i[show edit update destroy]

  def index
    @internalps = Product.order(created_at: :desc)
  end

  def show
  end

  def new
    @internalp = Product.new
  end

  def edit
  end

  def destroy
   @internalp.destroy
   redirect_to office_products_path, status: :see_other, notice: "Product was successfully destroyed."
  end

  private

  def product_params
    params.require(:product).permit(:title, :content, :avatar, :status, :ptype, user_ids:[], images:[])
  end

  def set_product
    @internalp = Product.find(params[:id])
  end

end

app/controllers/office/rooms_controller.rb
class Office::RoomsController < OfficeController

  before_action :authenticate_user!

  def index
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)

    render "index"
  end

  def show
    @single_room = Room.find(params[:id])
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)
    @message = Message.new
    @messages = @single_room.messages.order(create_at: :asc)

    render "index"
  end

end

app/controllers/office/salaries_controller.rb
class Office::SalariesController < OfficeController

  def year
    @years = Year.all
    @year = Year.find(params[:id])
    @months = Month.all
    @users = User.where.not(work_group: "User")
    @salaries = Salary.all
  end

  def month
    @month = Month.find(params[:id])
    @year = Year.find(params[:year_id])
    @users = User.where.not(work_group: "User")
    @salaries = Salary.all
  end

  def project
    @user = User.find(params[:id])
    @months = Month.all
    @year = Year.find(params[:year_id])
  end

  def new
    @salary = Salary.new
  end

end

app/controllers/office/static_back_pages_controller.rb
class Office::StaticBackPagesController < OfficeController
  def index
  end

  def team
    @userspm = User.where(role: "Project Manager")
    @userswd = User.where(role: "Web Designer")
    @usersbd = User.where(role: "Back-end Developer")
    @usersfd = User.where(role: "Front-end Developer")
  end
end

app/controllers/office/users_controller.rb
class Office::UsersController < OfficeController

  def show
    @user = User.find(params[:id])
    @users = User.all_except(current_user)

    @room = Room.new
    @rooms = Room.public_rooms
    @room_name = get_name(@user, current_user)

    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)

    @message = Message.new
    @messages = @single_room.messages.order(create_at: :asc)

    render "office/rooms/index"
  end

  def profile
    @user = User.find(params[:id])
  end

  def salary
    @user = User.find(params[:id])
    @months = Month.all
    @year = Year.find(params[:year_id])
    @salaries = Salary.all
    @invoices = Invoice.all
  end

  private

  def get_name(user1, user2)
    user = [user1, user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end
end

app/controllers/office_controller.rb
class OfficeController < ApplicationController
  #before_action :authenticate_user!
end

app/views/office/static_back_pages/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/office/static_back_pages/docs.html.erb
<% if current_user.role == "Project Manager" %>
  <section class="dark:bg-gray-800 dark:text-gray-100">
    <div class="container flex flex-col justify-center px-4 py-8 mx-auto md:p-8">
      <h2 class="text-2xl font-semibold sm:text-4xl">Skills that are needed for <%= current_user.role %></h2>
      <p class="mt-4 mb-8 dark:text-gray-400">Here are the skills needed to reach a certain level</p>
      <div class="space-y-4">
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Junior beginner</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Junior advanced</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Junior Upper</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Middle beginner</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">...</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
      </div>
    </div>
  </section>
<% elsif current_user.role == "Web Designer" %>
  <section class="dark:bg-gray-800 dark:text-gray-100">
    <div class="container flex flex-col justify-center px-4 py-8 mx-auto md:p-8">
      <h2 class="text-2xl font-semibold sm:text-4xl">Skills that are needed for <%= current_user.role %></h2>
      <p class="mt-4 mb-8 dark:text-gray-400">Here are the skills needed to reach a certain level</p>
      <div class="space-y-4">
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Junior beginner</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Junior advanced</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Junior Upper</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Middle beginner</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">...</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
      </div>
    </div>
  </section>
<% elsif current_user.role == "Back-end Developer" %>
  <section class="dark:bg-gray-800 dark:text-gray-100">
    <div class="container flex flex-col justify-center px-4 py-8 mx-auto md:p-8">
      <h2 class="text-2xl font-semibold sm:text-4xl">Skills that are needed for <%= current_user.role %></h2>
      <p class="mt-4 mb-8 dark:text-gray-400">Here are the skills needed to reach a certain level</p>
      <div class="space-y-4">
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Junior beginner</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">English - Pre-intermediate</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">Basic knowledge of the Ruby language (syntax, methods, basic data types, debugging, rubygems)</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Junior advanced</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">English - Intermediate</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">Basic knowledge of the Ruby language (syntax, methods, basic data types, debugging, rubygems)</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">Work experience - 6 month</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Junior Upper</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">English - Intermediate</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">Basic knowledge of the Ruby language (syntax, methods, basic data types, debugging, rubygems)</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">Work experience - 1 year</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Middle beginner</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">...</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
      </div>
    </div>
  </section>
<% elsif current_user.role == "Front-end Developer" %>
  <section class="dark:bg-gray-800 dark:text-gray-100">
    <div class="container flex flex-col justify-center px-4 py-8 mx-auto md:p-8">
      <h2 class="text-2xl font-semibold sm:text-4xl">Skills that are needed for <%= current_user.role %></h2>
      <p class="mt-4 mb-8 dark:text-gray-400">Here are the skills needed to reach a certain level</p>
      <div class="space-y-4">
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Junior beginner</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Junior advanced</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Junior Upper</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">Middle beginner</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
        <details class="w-full border rounded-lg">
          <summary class="px-4 py-6 focus:outline-none focus-visible:ring-violet-400">...</summary>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
          <p class="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">...</p>
        </details>
      </div>
    </div>
  </section>
<% end %>

app/views/office/static_back_pages/index.html.erb
<section class="bg-gray-800 text-gray-100">
  <div class="container flex flex-col items-center p-4 mx-auto md:p-8 mt-20">
    <div class="flex flex-col w-full sm:flex-row sm:divide-y-0 sm:divide-x sm:px-8 lg:px-12 xl:px-32 divide-gray-700">
      <div class="flex flex-col w-full divide-y divide-gray-700">
        <%= link_to "My profile", office_user_profile_path(current_user), class: "flex items-center justify-center p-4 sm:py-8 lg:py-12"%>
        <%= link_to "Messages", office_rooms_path, class: "flex items-center justify-center p-4 sm:py-8 lg:py-12"%>
        <%= link_to "Docs", office_docs_path, class: "flex items-center justify-center p-4 sm:py-8 lg:py-12"%>
      </div>
      <div class="flex flex-col w-full divide-y divide-gray-700">
        <%= link_to "Our team", office_team_path, class: "flex items-center justify-center p-4 sm:py-8 lg:py-12"%>
        <%= link_to "Products", office_products_path, class: "flex items-center justify-center p-4 sm:py-8 lg:py-12"%>
        <%= link_to "Forum", forums_path, class: "flex items-center justify-center p-4 sm:py-8 lg:py-12"%>
      </div>
      <div class="hidden w-full sm:flex-col sm:flex divide-y divide-gray-700">
        <%= link_to "Settings", edit_user_registration_path, class: "flex items-center justify-center p-4 sm:py-8 lg:py-12"%>
        <%= link_to "Back", root_path, class: "flex items-center justify-center p-4 sm:py-8 lg:py-12"%>
        <%= link_to "Exit", destroy_user_session_path, class: "flex items-center justify-center p-4 sm:py-8 lg:py-12"%>
      </div>
    </div>
  </div>
</section>

app/views/office/static_back_pages/team.html.erb
<section class="py-6 dark:bg-gray-800 dark:text-gray-100 mt-12">
  <div class="container flex flex-col items-center justify-center p-4 mx-auto space-y-8 sm:p-10">
    <h1 class="text-4xl font-bold leading-none text-center sm:text-5xl mb-24">Our team</h1>
    <h3 class="font-bold leading-none text-center text-2xl">Project Manager</h3>
    <div class="flex flex-row flex-wrap-reverse justify-center">
      <% @userspm.each do |userspm| %>
        <%= link_to (office_user_profile_path(userspm.id)) do %>
          <div class="flex flex-col justify-center m-8 text-center">
            <% if userspm.avatar.attached? %>
              <%= image_tag userspm.avatar, class: "self-center flex-shrink-0 w-24 h-24 mb-4 bg-center bg-cover rounded-full dark:bg-gray-500"%>
            <% else %>
              <img class="self-center flex-shrink-0 w-24 h-24 mb-4 bg-center bg-cover rounded-full dark:bg-gray-500" src="https://st2.depositphotos.com/47577860/46283/v/450/depositphotos_462836132-stock-illustration-assassin-deadpool-face-icon.jpg" alt="">
            <% end %>
            <p class="text-xl font-semibold leading-tight"><%= userspm.name %> <%= userspm.last_name %></p>
            <p class="dark:text-gray-400"><%= userspm.role %></p>
          </div>
        <% end %>
      <% end %>
    </div>
    <h3 class="font-bold leading-none text-center text-2xl">Web Designer</h3>
    <div class="flex flex-row flex-wrap-reverse justify-center">
      <% @userswd.each do |userswd| %>
        <%= link_to (office_user_profile_path(userswd.id)) do %>
          <div class="flex flex-col justify-center m-8 text-center">
            <% if userswd.avatar.attached? %>
              <%= image_tag userswd.avatar, class: "self-center flex-shrink-0 w-24 h-24 mb-4 bg-center bg-cover rounded-full dark:bg-gray-500"%>
            <% else %>
              <img class="self-center flex-shrink-0 w-24 h-24 mb-4 bg-center bg-cover rounded-full dark:bg-gray-500" src="https://st2.depositphotos.com/47577860/46283/v/450/depositphotos_462836132-stock-illustration-assassin-deadpool-face-icon.jpg" alt="">
            <% end %>
            <p class="text-xl font-semibold leading-tight"><%= userswd.name %> <%= userswd.last_name %></p>
            <p class="dark:text-gray-400"><%= userswd.role %></p>
          </div>
        <% end %>
      <% end %>
    </div>
    <h3 class="font-bold leading-none text-center text-2xl">Front-end Developer</h3>
    <div class="flex flex-row flex-wrap-reverse justify-center">
      <% @usersfd.each do |usersfd| %>
        <%= link_to (office_user_profile_path(usersfd.id)) do %>
          <div class="flex flex-col justify-center m-8 text-center">
            <% if usersfd.avatar.attached? %>
              <%= image_tag usersfd.avatar, class: "self-center flex-shrink-0 w-24 h-24 mb-4 bg-center bg-cover rounded-full dark:bg-gray-500"%>
            <% else %>
              <img class="self-center flex-shrink-0 w-24 h-24 mb-4 bg-center bg-cover rounded-full dark:bg-gray-500" src="https://st2.depositphotos.com/47577860/46283/v/450/depositphotos_462836132-stock-illustration-assassin-deadpool-face-icon.jpg" alt="">
            <% end %>
            <p class="text-xl font-semibold leading-tight"><%= usersfd.name %> <%= usersfd.last_name %></p>
            <p class="dark:text-gray-400"><%= usersfd.role %></p>
          </div>
        <% end %>
      <% end %>
    </div>
    <h3 class="font-bold leading-none text-center text-2xl">Back-end Developer</h3>
    <div class="flex flex-row flex-wrap-reverse justify-center">
      <% @usersbd.each do |usersbd| %>
        <%= link_to (office_user_profile_path(usersbd.id)) do %>
          <div class="flex flex-col justify-center m-8 text-center">
            <% if usersbd.avatar.attached? %>
              <%= image_tag usersbd.avatar, class: "self-center flex-shrink-0 w-24 h-24 mb-4 bg-center bg-cover rounded-full dark:bg-gray-500"%>
            <% else %>
              <img class="self-center flex-shrink-0 w-24 h-24 mb-4 bg-center bg-cover rounded-full dark:bg-gray-500" src="https://st2.depositphotos.com/47577860/46283/v/450/depositphotos_462836132-stock-illustration-assassin-deadpool-face-icon.jpg" alt="">
            <% end %>
            <p class="text-xl font-semibold leading-tight"><%= usersbd.name %> <%= usersbd.last_name %></p>
            <p class="dark:text-gray-400"><%= usersbd.role %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>